### ISSUE TITLE
iLIDS-VID

### ISSUE THREAD

**Issue by TragedyN** [deropty/PiT#2]
Thanks for your great work! I found the link for downloading the iLIDS-VID dataset is 404 now, can you plz share the dataset?  Thx!!!

**Comment by deropty** [comment]
> Thanks for your great work! I found the link for downloading the iLIDS-VID dataset is 404 now, can you plz share the dataset? Thx!!!

 You can download this dataset from this [link](https://pan.baidu.com/s/1qFMA5khlJINBKSm0dRcN1A) (code: 885u).

**Comment by TragedyN** [comment]
Thx for your reply, I found this link does not contain splits.json file, where can I  find it?

**Comment by deropty** [comment]
I have forgotten the source link of the split.json file. But you can use the file directly in the attached zip.
[splits.zip](https://github.com/deropty/PiT/files/8554044/splits.zip)

**Comment by TragedyN** [comment]
Thx for your help! Have a good day!!
