### ISSUE TITLE
Code for testing

### ISSUE THREAD

**Issue by mx10108287** [deropty/PiT#5]
Hi, I am trying to train the model, but I can't find the file test.py, where can I download that?

**Comment by deropty** [comment]
> Hi, I am trying to train the model, but I can't find the file test.py, where can I download that?

The code has been updated. You can test the trained model with the following command,
`$ python train.py --config_file configs/MARS/pit-test.yml MODEL.DEVICE_ID "('0')"`

**Comment by mx10108287** [comment]
Thank you!
